### ISSUE TITLE
[New Item] Bear Trap

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#100]
**Description:**
When placed creates a model on the ground that when walked over will ensnare them and do damage.

**Task Expectations/To Do:**
- [x] Create primative model on ground when player collides with it they take 20 damage and ensnared for 4 seconds. Maybe add bleed.
- [x] Spawn Rarity: Uncommon
- [x] Item Category: Utility
- [ ] Spawn On Hunter

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1292272025682837559/1292272025682837559
https://discordapp.com/channels/956245649534378124/1432430171805454458/1432430171805454458
