### ISSUE TITLE
[New Item] Frostbite Shotgun

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#103]
**Description:**
A shogun that gives hypothermia on hit.

**Task Expectations/To Do:**
- [x] Give 100 intensity hypothermia on hit for 8 seconds.
  - Since shotgun shots hit a lot probably just check if they already have hypothermia before giving the hypothermia.
- [x] Spawn Rarity: Epic
- [x] Item Category: Weapon

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1272962304480379001/1272962304480379001
