### ISSUE TITLE
[New Class] Implement Playable Flashbang In Normal Gameplay 

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#105]
**Description:**
Fix playable flashbang for normal gameplay and spawn it in a pedestal. 

**Task Expectations/To Do:**
- [ ] Fix bug where if a player picks up Flashbang and drops it they fall through the floor. (Might've already been fixed but make sure it is)
- [ ] Spawn the Flashbang
  - Playable flashbang should only have a 25% chance to spawn in a match. 
    - You can use the spawn chance property in the custom role though you will need to check that value when you spawn it.
  - Playable flashbang should spawn in a pedestal. I believe Ashley has made a spawn point for this pedestal. 
- [ ] Make sure everything about the flashbang is qa tested and fix any issues before release.  

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:**
https://discordapp.com/channels/956245649534378124/1224393793760137337/1224393793760137337
https://discordapp.com/channels/956245649534378124/1224846934624436326/1224846934624436326
https://discordapp.com/channels/956245649534378124/1279963337567764633/1279963337567764633

**Comment by TtroubleTT** [comment]
After recent April fools I have come to realize that I think april fools is special and should be kept that way or we wont have stuff for april fools. Also this class will becomes boring quick cause you cant actually do anything as it
