### ISSUE TITLE
[New Item] Enhancer-A

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#106]
**Description:**
A neurological enhancement that gives you a random ability.

**Task Expectations/To Do:**
- [x] Gives a random ability to the player who uses it.
  - Might not be the easiest because you have to figure out how to choose the default values. Might be best to choose a random special class that has abilities and then give the player all of those abilities or a random ability from that class using their default values.
  - Don't let it grant temporary abilities. For instance: Can't grant TemporaryInfiniteAmmoAbility but can grant the Activatable InfiniteAmmoAbility.
  - Can give an ability to a class that already has abilities.
  - You can probably use the Description property of the ability in the explanation message they get.
- [x] Spawn Rarity: Common.
- [x] Item Category: Enhancement.
- [x] Add 914 recipe like the other enhancers. Adrenaline on Very Fine 5% chance to create Enhancer-A.

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1280315416010293289/1280315416010293289
