### ISSUE TITLE
[New Item] Decoy

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#107]
**Description:**
Radio that can deploy dumbies to be used as decoys or shields.

**Task Expectations/To Do:**
- [x] When you drop the radio it creates a dumbie of the same class/name/custom info as the player with 100 HP and 50 AHP. Can be used 3 times before item is destroyed.
  - If the player spawning is a serpents hand the dumbie should be a serpents hand recruit.
  - Don't give it the players special class but change the custom info to have the players name and special class and hide the normal name (like spy). So that the dumbie can be used as a decoy.
  - Before this item is released dumbies will need to be compatible with exiled so that exiled specific stuff works on them.
- [x] Spawn Rarity: Uncommon
- [x] Item Category: Utility

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1252054465004179497/1252054465004179497
