### ISSUE TITLE
[New Item] SCP Communicator

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#108]
**Description:**
An device attuned to SCP's instead of the dead. Using it lets you talk to SCPs.

**Task Expectations/To Do:**
- [ ] The person who uses it can hear and talk in SCP chat while it is active.
  - Make sure they can't also hear/talk in spectator.
  - Only SCP allied classes can hear and talk other just hear static.
- [ ] Spawn Rarity: None
- [ ] Can spawn on a Serpents Recruit as its SCP item.
- [ ] Spawns on Leader 
- [ ] SCP-1576 25% chance 1 to 1 -> SCP-1576-A 
- [ ] Item Category: SCP

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discordapp.com/channels/956245649534378124/1279966523594641408/1279966523594641408
https://discord.com/channels/956245649534378124/1477061228638765290/1477061228638765290
