### ISSUE TITLE
[New Item] Distortion Grenade

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#109]
**Description:**
A throwable (grenade colors might not be free) that creates a sludge on the ground that distorts players views and actions.

**Task Expectations/To Do:**
- [ ] Throwable that spawns a sludge model on impact. When people walk into the model they will get blurred effect and amnesia items while inside and for 5 seconds after.
  - Just keep applying every tick for duration of 5 and it'll stay for 5 seconds.
- [ ] Spawn Rarity: Common
- [ ] Item Category: Grenade

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1287143287005646858/1287143287005646858
