### ISSUE TITLE
[New Item] Supply Drop

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#110]
**Description:**
When dropped a helicopter will drop off supplies on surface.

**Task Expectations/To Do:**
- [ ] When the player drops the radio the helicopter animation will play and where it lands it will spawn a custom model probably some kind of open crate that has goodies inside.
  - Number of items: 5-8 random items in the crate.
  - Have a list of possible items it can spawn both custom and normal. Stuff like Enhancers, other usable items and maybe even scp items and weapons.
    - Consider maybe using the fabrication object of MultiWeighedFabrication that lets you make rarity lists that you can put normal and custom items in. 
- [ ] Spawn Rarity: Rare
- [ ] Item Category: Utility

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1250895817565405365/1250895817565405365

**Comment by Ashley101011** [comment]
![Image](https://github.com/user-attachments/assets/0992cdb6-3306-4caf-ae34-c33de6fd2a37)


schematic has animations here the controller with the names
