### ISSUE TITLE
[New Item] Coin Of Chaos

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#111]
**Description:**
A coin that when flipped causes chaos by doing random things.

**Task Expectations/To Do:**
- [ ] Random things happen when you flip the coin. You can take inspiration from the discord suggestion. You don't have to do everything it suggests and you can add ideas you want.
  - Just make sure the stuff that you do is easy to maintain. If one random thing it does takes a lot of code lines its not worth it. Pick stuff that still lets you keep the code neat. 
  - This is probably something that should be its own pull request just cause of how messy the code can get it may need a lot of reviews.
- [ ] Spawn Rarity: Rare
- [ ] Item Category: Troll

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1269738056672481361/1269738056672481361
