### ISSUE TITLE
[New Item] Anti SCP-244-B

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#112]
**Description:**
A vase that is hot. Gives burned effect while in inventory and upon placing/dropped shatters and creates a molotov fire.

**Task Expectations/To Do:**
- [x] While in inventory give burned effect.
- [x] On placing/dropped the item is destroyed and a molotov fire spawns for 10 seconds.
- [x] Spawn Rarity: None
- [x] 10% chance to replace normal SCP-244-B
- [x] Item Category: Troll

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1296671917415206963/1296671917415206963
