### ISSUE TITLE
[New Item] SCP-1853-A

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#115]
**Description:**
A SCP-1853 that will let you always have 3 danger stacks at least.

**Note:**
If you have a better idea for the name please do.

**Task Expectations/To Do:**
- [x] When they use this SCP-1853 it will give them 3 danger stacks.
  - They should still be able to gain more than 3 danger stacks like normal SCP-1853 but they should never be able to go below 3 danger stacks.
- [x] Spawn Rarity: None
- [x] Item Category: Utility
- [x] 10% chance to replace normal SCP-1853

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1285501039902199890/1285501039902199890
