### ISSUE TITLE
[New Item] SCP-207-A

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#116]
**Description:**
A SCP-207 that gives you more speed than normal and lets you stack speeds higher.

**Note:**
If you have a better idea for the name please do.

**Task Expectations/To Do:**
- [x] When this SCP-207 is used the player will also get a 10% movement boost. Any further SCP-207 used (even normal SCP-207) will also grant a 10% movement boost each.
  - Make sure these movement boosts stack together but don't just get the intensity or someone could use speed pills and then this to exploit. x3rt effect api when out will probably be helpful.
  - Any previous SCP-207 that were taken should give a 10% boost each. Ex: If a player took 2 SCP-207 previously then took SCP-207-A they would get the normal 10% movement boost from SCP-207-A and a 10% for the 2 before which would be a 30% movement boost.
- [x] Spawn Rarity: None
- [x] Item Category: Utility
- [x] 10% Chance to replace SCP-207

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1285501039902199890/1285501039902199890
