### ISSUE TITLE
[New Item] SCP-268-A

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#117]
**Description:**
A SCP-268 that gives true invisibility. 

**Note:**
If you have a better idea for the name please do.

**Task Expectations/To Do:**
- [x] On use it will give the player true invisibility. SCP-096 can't see when you triggered them, SCP-079 can't see, etc. You cannot use items but can open doors.
  - Can probably use the disguise as spectator.
- [x] Spawn Rarity: None
- [x] Item Category: Utility
- [x] Has 10% chance to replace SCP-268.

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1285501039902199890/1285501039902199890
