### ISSUE TITLE
[New Item] SCP-1344-A

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#118]
**Description:**
A modified SCP-1344 that doesn't give you blindness.

**Note:**
If you have a better name please do.

**Task Expectations/To Do:**
- [x] When worn you get the normal SCP-1344 but without the blindness.
  - If possible also not give severed eyes when removing.
- [x] Spawn Rarity: None
- [x] Item Category: Utility
- [x] 10% chance to replace SCP-1344.

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1285501039902199890/1285501039902199890
