### ISSUE TITLE
[Rework] Inventory Armor Changes

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#124]
**Description:**
Adding custom armor to special classes.

**Task Expectations/To Do:**
- [x] Make sure Electric protection armor is fixed and doesn't error.
- [x] Make sure Biohazard Armor is fixed and doesn't error.
- [x] Electrician spawn with Electric Protection Armor over normal armor.
- [x] Alchemist spawn with Biohazard Armor over normal armor.

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1289360749923274813/1289360749923274813

**Comment by RealNicoPlayer** [comment]
Attempting to fix since I don't have much information.
