### ISSUE TITLE
[Idea] Primative Map Ability

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#127]
**Description:**
An ability when pressing LEFT ALT shows a map of the zone you are in with a red circle where you are.

**Task Expectations/To Do:**
- [ ] Pressing LEFT ALT creates a map of the zone you are in using primative squares. Pressing LEFT ALT again will close the map.
- [ ] There should be a red dot or some kind of indicator where you are.
- [ ] Stretch goal would be showing enemy dots also on the map. Potentially even moving.
- [ ] Original suggestion was for tracker though if you can see enemies potentially using this for serpents hand hacker rework could be cool. 

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1286719993165119568/1286719993165119568

**Comment by TtroubleTT** [comment]
Ashley was working on making room models for stuff tho it might just be easier for the programer to make primative cubes in code of the rough size of the room
