### ISSUE TITLE
[QA Tool] 100 Damage Gun

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#132]
**Description:**
A gun to help QA test damage reduction.

**Task Expectations/To Do:**
- [x] Com 18 that should do 100 damage on hit.
  - This 100 damage should be effected by damage reduction effect and our custom way of doing damage reduction.
- [x] Spawn Rarity: None
- [x] Item Category: Admin

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** QA Requested.
