### ISSUE TITLE
[New Feature] SCP Swap

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#134]
**Description:**
A command that SCPs can use to swap SCPs with each other.

**Task Expectations/To Do:**
- [x] SCPs can run a command that lets them send a request to another scp to swap with them.
  - They can only swap with an scp that exists they cannot just choose what scp they want to become. 
- [x] If an SCP has a swap request they can accept it and they will swap SCP with the person that requested.
  - More than 1 request can happen so make sure there is a way they can choose between requests.
- [x] SCPs should not be able to swap after 30 seconds into the round. 
  - Try to avoid any courtines and call delays you can probably just use round times to check and that 30 seconds in is when any swap request time out too. 
- [x] Remember SCPs can .human so if someone .humans the request needs to be killed.
- [x] Scps should also get the custom role of who they swap with.

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1260368275171311636/1260368275171311636
