### ISSUE TITLE
[API] Effect API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#135]
**Description:**
A way to keep track of effects in a que so that effects are not overridden. 

**Task Expectations/To Do:**
- [x] All effects given have a sort of que with the same effects. The highest intensity of the effects will have priority for its duration then when its up if there were other effects that still have duration their intensity will be applied. 
  - Ex: Player gets a 2 intensity cola effect for 15 seconds. Then gets a 4 intensity cola effect for 10 seconds.  Then gets a 3 intensity cola effect for 5 seconds. Then gets a 1 intensity cola effect for unspecified (infinite till turned off) seconds. The player will be on 4 intensity cola. After 5 seconds is up the 3 intensity cola will no longer be in the que the player will still be using the 4 intensity cola. After 10 seconds (5 seconds after we lost the 3 intensity from the que) the 4 intensity cola is out of the que and we move to using the 2 intensity cola. After 15 seconds (5 more seconds since we lost the 4 intensity) the 2 intensity is up and we move to using the 1 intensity cola which will be used until disabled.
- [x] Adding a higher intensity then what is used to already active processes will put it as the one to get the intensity from.
- [x] Disabling an effect should disable all of the que though there should also be a way to remove specific things from the que. 
- [x] Preferably use as little exiled stuff as possible as it'll be easier to port to lab api.

Fixes ChaosTheoryScp/IssueTracker/issues/170

**Comment by TtroubleTT** [comment]
Finished
