### ISSUE TITLE
[API] Disguise API Rework

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#136]
**Description:**
An update to disguise api to make it better and allow disguise ques.

**Task Expectations/To Do:**
- [x] Similar to x3rts effect ques there should be a way to que disguises. Priority would go to the most recent disguise.
  - Ex: A player is disguised as ClassD for 10 seconds. A player is disguised as an MTF for 5 seconds. Player will currently look like an mtf. Then player is disguised as Scientist for 8 seconds. The player will currently look like a scientist. After 5 seconds the MTF disguise will be removed from the que. The player will still look like a scientist. After 8 seconds (3 more seconds from removing the mtf disguise from que) the scientist disguise will be removed from the que. The player will now look like a ClassD . After 10 seconds (2 more seconds from scientist being removed from que) the class d disguise is removed from que. Since there is no more disguises in que they will look normal. 
- [x] Un Disguising a player should remove all their disguises from the que and make them normal. 
- [x] There should be a way to remove specific disguises from the que. Possibly still using UnDisguise but with an optional paramter of the tag to remove. 
- [x] Move away from using components. Instead you can use something similar to how effect api keeps track of stuff. There can be a class that keeps track of the ques and individual disguise info. 
- [x] The way to disguise should still be static player extensions.
- [x] If the player is affected by the active disguise but another disguise has their roletype they get that while others can get from a diff disguise info. Cache in dictionary what role a player is maps to what disguise info. Basically active disguise but per role.
