### ISSUE TITLE
[API] AHP API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#137]
**Description:**
Way to add AHP not using EXILED stuff where we can have an actual max ahp.

**Task Expectations/To Do:**
- [x] Make methods for adding AHP that uses basegame stuff instead of exiled stuff. Should have all functionality that exiled has.
- [x] There should be a way to set an overall maximum that the current ahp that the player actually has (from all the proceses) won't go above. 
- [x] Each process already has a maximum but those max don't respect each other. The maximum for the process should respect ahp gotten from other processes. 
  - Ex: Armor specialist AHP can't go above 30. So when using SCP-500-V they can get more than 30 ahp from SCP-500-V but they should not continue getting AHP from armor specialist. Armor specialist should only continue giving AHP once the players current overall ahp goes below 30.
- [ ] Move all AHP stuff to this new system and test to make sure this is fixed https://github.com/ChaosTheoryScp/IssueTracker/issues/9

**Comment by RealNicoPlayer** [comment]
Current tasks are finished but a bit of stuff is missing.

**Comment by TtroubleTT** [comment]
Done in Lab api
