### ISSUE TITLE
[API] Dumbie API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#138]
**Description:**
Making dumbies easily spawnable and make them act as players in regards to plugins.

**Task Expectations/To Do:**
- [ ] Easy methods for spawning/unspawning dumbies.
- [ ] If we are still using Exiled make sure they act as an exiled player so plugins actually work with them.
- [ ] A player extension that checks if someone is a Dumbie. 

**Developer Note:**
There is a good chance that Lab Api will make wrappers for dumbies that basically does this for us.

**Comment by TtroubleTT** [comment]
Lab api already does this
