### ISSUE TITLE
[API] Audio API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#139]
**Description:**
An api for playing audio to players.

**Task Expectations/To Do:**
- [ ] Methods for playing audio easily with volume, etc using Admin Speaker Toy. 
- [ ] Ability to play sounds based on proximity (I believe this is the default).
- [ ] Way to play audio to everyone. AKA music for FBIs music.
