### ISSUE TITLE
[API] Custom Item API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#140]
**Description:**
Custom item api to move away from exiled. 

**Task Expectations/To Do:**
- [x] Custom item api similar to how ability api is. No need for dictionaries there is instance for each custom item. 
- [x] Way to get an items custom item (similar to GetCustomAbilities).
- [x] Way to do ticking stuff with custom item.
- [x] Firearm custom item with ability to set max ammo etc. 
- [x] Universal ways to do cooldowns for items.
- [x] Handle lack of being able to upgrade in item base and let it be a settable property.
- [ ] ~~Deployables check with x3rt we had discussed something about the items that deploy something like the Barricade are its own thing once spawned.~~
- [x] Add light colors to items in itemBase
- [x] Add ItemSpawnRarity property from our exiled version
- [x] Add ItemCategory property from our exiled version

**Comment by x3rt** [comment]
> Move escape logic to the item base with stuff that can be overridden.

What does this mean? What logic?
??

**Comment by x3rt** [comment]
Because escaping with custom items works fine?
