### ISSUE TITLE
[API] Custom Role API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#141]
**Description:**
Custom role system not using exiled.

**Task Expectations/To Do:**
- [x] Similar to ability api - Unique instances of roles instead of one that is shared between all players.
- [x] No need for cooldown stuff from our old api but make better way for adding the abilities. 
- [x] NameId for what we use for commands no spaces. Name which can have spaces and is used for the custom info.
- [x] Get Rid of SetCTSpecialClasses. No delay way to add the role that shows the name and description without all the weird stuff in setctspecial classes.
- [x] Color property to set for the name the hint of what the name of the class is. This way we don't have to do weird stuff to give SCP-035 name a red name in the hint.
  - Color property is added we just need the actual hint set up with HintAPI to be able to finish this. https://github.com/ChaosTheoryScp/IssueTracker/issues/382
- [x] We add colors to specific stuff in the description instead of the yellow we have
- [x] Spawn system without teleport.
  - Let it be an override to declare what room and what relative position it spawns in and handles the spawning under the hood. This should be a list that also lets you declare the rarity of the spawn.
  - Have option to be able to be able to declare the RoleSpawnPoint used in basegame to use any basegame spawn point based on a role.
- [x] No more using RoleType.None there should be a way to declare that this role should be added but not change the players current role. And a way to also set the role declared itself.
  - This will stop us from having multiple of basically the same classes.
- [x] Either port this if its already made or add functionality for it https://github.com/ChaosTheoryScp/IssueTracker/issues/142 
- [x] Complete this task for letting abilities be removed on escape https://github.com/ChaosTheoryScp/IssueTracker/issues/385 
- [x] Add list for adding items to player when they escape in addition to keeping their items.
  - Needs extensions for the item.GiveTo.
- [x] Faction property for their friendly fire stuff. 
  - https://github.com/ChaosTheoryScp/IssueTracker/issues/381
- [x] Finish ToDo: Add extension method item.GiveTo(Owner).
  - Pretty sure this is for being able to give item no matter if its basegame or custom.
  - Also add item.RemoveFrom(Owner) for the DTO
- ~~[ ] Add being able to give specific candies using the ItemDTO and the item.GiveTo extension.~~
- ~~[ ] ToDo: Add Scale setting on add role and set back to remove role.~~
