### ISSUE TITLE
[API] Rewrite Spawn System

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#143]
**Description:**
Abstracts the system for spawning our own scps.

**Task Expectations/To Do:**
- [x] Abstract how we spawn scps it should not be all shoved in round start like it currently is. 
- [x] In general the spawn system should be rewritten better. Potentially have a base spawning class and then classes that inherit like custom scp, normal scp, special classes, scp special classes. This way we have separated logic instead of haphazardly throwing it all into round start. 
- [x] Should have a way of spawning any custom scp we have easily and adding new custom scps to the spawn system easily
  - Should also work for basegame SCPs like SCP-3114 if it comes back to be easily integrated in the spawn system.
- [x] There should be a default where every custom SCP has an equal chance of spawning roughly the same math the SCP-035 currently uses. There should also be a way to put a spawn rarity that is lower or higher. You can probably use the current spawn rarity. 
- [x] SCP Special classes by default should chose a random one but let it also have rarities if we decide to use it. 
- [x] Would also be nice to have spawn rarity work with normal special classes in case we want to use it but it defaults to equal.
