### ISSUE TITLE
[API] Scenario API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#144]
**Description:**
A way to handle different scenarios happening.

**Task Expectations/To Do:**
- [x] Add a scenario base class that will handle the logic for a scenario being picked every round. 
- [x] This class should have a way to declare the rarity of the scenario.
  - Make sure in the Scenario picker it shuffles the list of scenarios before checking the rarity.
  - Serpents is the default scenario and should be chosen if no scenario is picked. Though serpents scenario should still be able to be picked via rarity just so non serpents scenario doesn't have an advantage. 
- [x] Each scenario should inherit from Scenario Base and and all scenario spawning logic etc should be in this class not a random event handler.
- [x] Make this API easy to re use. Its first purpose will be for SCP based scenarios but in the future I think it would be cool to also have a different section of scenarios that benefit humans and ones that benefit nobody that don't intertwine with the other scenario types.

**Comment by TtroubleTT** [comment]
Finished
