### ISSUE TITLE
[API] Hint API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#145]
**Description:**
A way to give hints where you can have multiple hints on screen at once.

**Task Expectations/To Do:**
- [x] Way to display multiple hints at one. Sending a hint adds it to the current hint pool.
- [x] Able to specific position of hint using enum of hint quadrant for easy use.
  - Make sure this doesn't shift other hints.
- [x] Ability to specific length of hint.
- [x] Use as little exiled stuff as possible.
- [x] Move all current stuff to new hint system. (Trub can also do this part as I have specific places I want things)

**Developer Note:**
These are public hint systems that might be useful for seeing how they work.
https://github.com/moddedmcplayer/AdvancedHints
https://github.com/Ruemena/RueI

**Comment by TtroubleTT** [comment]
For some reason didnt close in merge
