### ISSUE TITLE
[API] 914 API

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#147]
**Description:**
Cleaning up the current code and allowing more options for our 914 upgrading.

**Task Expectations/To Do:**
- [ ] Add ability to upgrade all kinds of ways.
  - Normal Item -> Custom Item
  - Custom Item -> Normal Item
  - Normal Item -> Normal Item
  - Custom Item -> Custom Item
  - The best way to do this may honestly be using a similar set up we did to fabrication where you take in an object that lets you give a custom item or normal item and then a method that does the type of upgrading depending. 
- [ ] Since an item has a chance to become more than one thing the list should be shuffled every time so that its more random rather than prioritizing first things.  

- [ ] Recipe's to Add:
  - Medkit Coarse 25% chance -> Anti Medkit
  - Anti Medkit Fine 25% chance -> Medkit
  - Painkillers Coarse 25% chance -> Painmakers
  - Painmakers Fine 25% chance -> Painkillers 
  - SCP-500 Coarse 25% chance -> Anti SCP-500
  - Anti SCP-500 Fine 25% chance -> SCP-500
  - Cola chance to become anti cola on 1 to 1
  - You can 1 to 1 through Enhancers
  - You can 1 to 1 though AntiMedkit -> Painmakers -> Anti SCP-500
  - Most custom items on Rough become their base item 25% chance. Not for problematic weapons like tranqgun. 
  - Normal Items on very fine have chances to become one of the upgraded versions of that item on low chance. Ex: 5% chance E11 to PoisonRifle, 5% chance E11 Sniper Rifle, etc.
  - Can cycle through SCP-1499 -> SCP-3660, -> other custom items that use hat.
  - Fn5 1 to 1 to Shank. Visa Versa. 
  - 3-bang-X 1 to 1 -> 3-bang-F. Visa Versa. 
  - Coin custom items can one to one.
  - Neuroenhancer and scp enhancer one to one.
  - If you want to add recipes you feel make sense feel free to. 

Jailbird swap https://discord.com/channels/956245649534378124/1393082290682466314/1393082290682466314

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** 
https://discord.com/channels/956245649534378124/1190916472067858492/1190916472067858492
https://discord.com/channels/956245649534378124/1272453412096839720/1272453412096839720
https://discord.com/channels/956245649534378124/1298763782532628533/1298763782532628533

https://discord.com/channels/956245649534378124/1150266954800693328/1150266954800693328
