### ISSUE TITLE
[API] Server Specific Settings API 

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#148]
**Description:**
Properly setting up server specific settings stuff.

**Task Expectations/To Do:**
- [x] Properly set up a system for server specific settings and easy to use methods.
- [x] Settings for Hints
- [x] Custom keybinds
  - [x] One item keybind for doing an action with a custom item (instead of using dropping)
  - [x] Keybind for showing special class and special item info (help).
  - [x] https://github.com/ChaosTheoryScp/IssueTracker/issues/537
