### ISSUE TITLE
[API] Achievements

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#149]
**Description:**
Server side Achievements. If database is done then do from database if not we can cope with exploits and use Server Specific Settings. 

**Task Expectations/To Do:**
- [ ] Show all possible achievements in server specific settings with some way to denote its been granted.
- [ ] Let players press and hold to reset the achievement. 
- [x] Make sure you didn't miss any achievements from jokers dms. 
- [x] Achievement Ideas: https://discord.com/channels/956245649534378124/1201442028861534248/1201442028861534248
- [ ] Try to add achievement's for every custom class / item
- [ ] Below Achievements:
  - [ ] Pill chugger: eat 5 or more funny pills in one round
  - [ ] Get off my lawn: Be guard and kill all serpents that spawn
  - [ ] Evil Spawn Point Placer Who?: Find all 202 pill spots
  - [ ] Protect And Serve - As a Facility Guard, eliminate 4 Chaos Insurgency before they reach Heavy Containment Zone.
  - [ ] Destructive Containment - Participate in the recontainment of every SCP without dying, as a Facility Guard.
  - [ ] RNGesus Loves Me - Escape the facility in under 60sec.
  - [ ] I have the Zoomies - Survive 4 min with a cola (rebalance minutes)
  - [ ] Traitor! - Betray your team and kill someone
  - [ ] Fufilling your role - Clean up 5 173 Tantrums as Janitor
  - [x] Server Technician Curse - Kill a Server Technician within first 20 seconds of the game
  - [ ] And they Say Counter Unit is bad - Kill entire Chaos spawn as counter unit
  - [x] Guardian Angel - Do 3x your health worth of healing to other players as a medic in a single life.
  - [ ] Vengence - As Vigilante help kill and scp and contribute to over 50% of the damage
  - [x] Professional Bodybuilder - As a Class-D Brute, open 3 gates before escaping the facility.
  - [x] Are you proud of me now? - Kill someone with the FN-5 2-4 damage gun
  - [x] Size Doesn't Matter - Get kills on 3 human players player before escaping as a Dwarf.
  - [x] Restraining Order - Kill the same player 3 times in the same round as a Chaos Stalker.
  - [ ] Not with my Squad - Contribute to killing and SCP as the Head Guard with at least one more guard participating.
  - [x] Me and THIS army  - Summon 10+ troops with detachment commander
  - [x] Say hello to my little friends - Summon Mini Reinforcements.
  - [x] Mission Accomplished - Achieve an NTF victory without dying as a Vigilante.
  - [x] Riot Police - Escort 3 Class-D to the escape zone and convert them to your team as Cell Guard.
  - [x] KOS IS FUN - Kill all alive dclass
  - [ ] Well this is annoying - Imobalize an SCP 3 times with the tranq gun
  - [ ] Hammer of Justice - Get 6 kills on enemy players as a Serpent's Hand Enforcer.
  - [ ] 360 No Scope - Kill Someone with the sniper while under 10 hp
  - [ ] Martyrdom - Killing someone with your martyrdom grenade as Chaos Bomber
  - [ ] T.I.D.E.S. - Turn the tide of battle by consuming every special enhancer in a single life.
  - [ ] Spacegun go brrr - Kill an SCP with the X7 Plasma Cannon
  - [x] May God have Mercy On your Soul - Kill someone with the Com-45 on steriods
  - [x] Darwinism - Win a match as SCP-035 after evolving.
  - [x] Public Execution - Kill someone with the jailbird as the Serpents Hand Executioner
  - [ ] Ambush Tactics - Kill 4 members of an NTF spawn wave before they enter Heavy Containment as the Chaos Spy.
  - [ ] Camping is not a strategy - Kill a player through the wall of a locked room as SCP-035.
  - [ ] Snake Tamer - Escape and become a serpents recruit
  - [ ] I JUST cleaned that! - Create a peanut tantrum as SH Janitor
  - [ ] Plot Twist - Escape the facility as a Scientist or Class-D, while having originally spawned as a militant class. (hidden achievement)
  - [ ] My Eyessssss - Flash someone with each flash of the 3-bang
  - [ ] Mock 10 - Get 200% speed boost from speed pills
  - [ ] Bullet Sponge - Absorb 3x your health worth of damage while under the affect of a single Hyper Adrenaline.
  - [x] Corrosive Results/ WTF Devs/ - Get teleported to the Pocket Dimension via SCP-914
  - [ ] Pewpewpewpew - Get 5 kills in a single use of the Bullet Storm
  - [ ] Oh, Why me?! - Get summoned as a zombie by a Serpent's Hand with SCP-500-A
  - [ ] Costume Party - Kill someone while under the effects of SCP-500-D
  - [ ] Better Living Through Chemistry - Reach a total max health of 200 (or more) from using SCP-500-H or get 100 hp worth of life from SCP-500-H to bypass jugg easy getting.
  - [ ] Go Touch Grass - Play 80 Hours in a week (hidden achievement)
  - [ ] Cluster Grenade - Kill someone with each explosion of a 3-bang
  - [ ] Uno Reverse Card - Kill a player within 5sec of them damaging you, while below 20 health.
  - [ ] Thats Just A Theory A Chaos Theory - Play as all the special classes and use all the custom items.
  - [ ] Extended Warranty - Save an ally by healing them with a MediGun while they have less than 10% life remaining. Must be done within 5sec of them taking damage and they must live for at least 30sec afterwards.
  - [x] REEEEvenge - After dying to a player as an SCP, kill that player during the same game round.
  - [ ] Not Today, F***ers - As an SCP, kill an entire NTF Spawn wave before they can enter the facility. Cannot be earned after the nuke detonates. Awarded to ever SCP that participates in killing the NTF wave.
 - [ ] Reproductive System - With more than 20 players total on the server, have half the servers population as zombies at the same time, as SCP-049
  - [ ] Praise the Holy Peanut - Escape the facility as Class-D after having looked at peanut for a total of 90sec, or convince peanut to escorts you to the escape zone.
  - [x] DENIED! - Get the killing blow on a player who has a killed at least 6 other players in their current life.
  - [ ] Gotta Catch em All - Get the killing blow on 4 players with a single SCP-018.
  - [ ] Masocist - Survive for 5 min after taking the painmakers
  - [ ] This Is Not A Bug - Die to painmakers in your next life.
  - [ ] A True Painmaker  - Die to the Painmakers 3 times in a single round.
  - [ ] That didn't even hurt - Gain a lott of hp as 035 from exploading people usingg pinkcandy or jailbird
  - [x] Nobody Expects The MTF Spy - Kill someone as the mtf spy
  - [x] Detaminment Specialist - Cuff SCP-035.
  - [ ] Nerd Rage - Late Spawn as SCP-096.
  - [ ] Bomberman - Kill 3 people with a single Pink Candy explosion.
  - [ ] Taco Bell Delivery Man - Cause 100 people to spawn Tantrums with the TacoDelux
  - [ ] Microwave Mechanic - Kill an SCP with the Micro After recharging using an ability. (Electromagnetic Researcher)
  - [ ] I Am the Law - Get banned by Trubby's Justice.
  - [ ] I said "NOT NOW", Mom! - Kill 8 players in a single enrage as SCP-096.
  - [ ] I'm The Boss Now - Become an NTF Captain via SCP-914.
  - [ ] The Safety of the Coin - Escape the facility with only a coin in your inventory after only having picked up a coin that round
  - [x] REVOLUTION - As a class D kill someone with the class D shank
  - [x] It is your Destiny - Escape with a full inventory of coins
  - [x] Who is the best now - kill shaft 5 times
  - [ ] Spooky Scary Skeletons - "Kill 10 players in a single round as SCP-3114"
  - [ ] Caffeine Fiend - Survive on cola on 035 for 10 min
  - [x] Fate Sealed - Blow up using the coin of destiny
  - [x] Balanced SCP - Get 50 kills as SCP-035 in the same round.
  - [x] Lend Me A Hand - Use Anti SCP-500.
  - [x] Apple A Day - Use all 3 anti healing items in one round. (painmakers, anti medkit, anti 500)
  - [x] God Amongst Men - Become a Legendary Zombie.
  - [ ] Taste Of Your Own Medicine - Use a sinkhole grenade on SCP-106.
  - [x] Running In the 90s - As a caffeine accustomed class reach max SCP-207.
  - [ ] Lets Go Gambling! - Blow up as Gambler from rolling both SCP-207 and Anti 207.
  - [x] Incognito - Killed 5 players with SCP-034 in the same life. 
  - [ ] Watch Your Step - Kill someone with a Landmine. 
  - [ ] Na Id Win - Be the last on your team when an enemy spawn wave spawns and win the round.
  - [ ] GunPowder Maniac - Use every custom grenade in one life.
  - [ ] True Leader - Survive till the next MTF spawn wave as a Commander.
  - [ ] Best Friends Forever - Survive as a Serpents Hand till the end of the round without any SCPs dying.
  - [ ] The 2020 Experience - Infect 10 players with the same radioactive virus.
  - [x] Anomalous Features - Kill someone while disguised as an SCP.
  - [ ] Disguise Artist - Kill 10 MTF as Serpents Mimic in one life/Recieve a medkit from a enemy.
  - [ ] Hot Potato - Kill a player with an impact grenade.
  - [ ] Viva La Resistance  - Use SCP-500-X to open light armory as a Class D.
  - [x] Homemade Snack - Eat Painmaker as Medic Guard.
  - [ ] JumpScare - Kill someone with a pounce within 5 seconds after coming out of invisibility as SCP-939-Hunter.
  - [ ] Antique Collector - Revive one zombie of each rarity in a single game.
  - [ ] Fetch! - Kill SCP-939 with SCP-018.
  - [ ] Always Trust The Coin Of Destiny - Survive flipping the coin of destiny.
  - [x] Your Labrat No Longer - Kill the Experimenter as the Test Subject.
  - [ ] My Pain Fuels Me - Kill a human class as Janitor while Masochism is active..
  - [ ] Sovereign's Subject - Kill an SCP as Eldritch Guard while under the effects of Hemocraft.
  - [x] Warped Timeline - Kill the Rampager as Enhancement Specialist.
  - [ ] I Always Come Back - Spawn as Bomber twice in a single round.
  - [ ] Your Prayers Are Answered - Use SCP-500-Q.
  - [x] Bow To Your King - Summon the Unreasonably Big Cube.
  - [ ] Counter Counter Unit - Kill a Counter Unit as a CounterUnit after betraying.
  - [ ] More Bullets Needed - Use bullet storm while wielding Com-45-On-Steriods.
  - [ ] Coward Unit - Use 05 teleport card as Counter Unit.
  - [ ] Wrong Class - Use SCP-207 as an Anti Rusher Class or Use a Anti 207 as a Rusher Class.
  - [ ] Third Eye Opened - Kill a player under the effects of 500-I.
  - [ ] 6ft Please - Infect a player as a plague bearer.
  - [ ] Gone With The Wind - Use SCP-500-T after getting below 20 health recently.
  - [x] Micronutrients - Eat a Micro as Consumer.
  - [x] Ain't Big Enough for the Two of Us - "As Outlaw or Gunslinger, kill the opposing cowboy.
  - [x] Waiter, More Copper. Please! - As consumer, eat 20 coins in a single round.
  - [ ] May Plague Befall Ye - As Plague Bearer spread cardiac arrest to an enemy.
  - [x] Opens Gate With Mind - As Brute open a gate with pry while hand cuffed.
  - [ ] Well Deserved Nap - Tranquilize a rusher two times in a row.
  - [ ] Unexpected Result - TP into a room that has an SCP in it. 
  - [x] Jumping Maniac - Jump 100,000 times. Hidden.
  - [ ] Trolled/WTF DEVS/Evil Developers - Teleport into tesla with 05 teleport card. Hidden.
  - [ ] This Feels Wrong - Summon SH Reinforcements as Serpents Hand Detachment Commander
  - [ ] Our battle shall be legendary - Have both Unreasonably big cube and duck lord in the same match.
  - [ ] Tranq/Watching Flashbang Someone in a tesla
