### ISSUE TITLE
[New Class] Class D Scrapper

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#74]
**Description:**
A Class D with a knack for breaking things and turning them into something new. Pressing LEFT ALT with an item in your hands will turn it into scrap. Pressing LEFT ALT with out an item in your hands will use your current scrap to make a new item.

**Task Expectations/To Do:**
- [x] Inventory: Coin, Flashlight.
- [x] Max Health: 100
- [x] Activatable Ability: Pressing LEFT ALT either turns an ability into scrap or makes an ability from scrap.
  - [x] Making Scrap: Pressing LEFT ALT with an item in your hand destroys the item and turns it into a certain amount of scrap depending on the item tier. 
    - Trash Tier Worth 0.25 Scrap: Coin, Flashlight
    - Low Tier Worth 1 Scrap: Low Tier Keycards, Medkit, Adrenaline, Painkillers, other easy to get items. You can probably make this the default tier and not a list and just make a list for everything else.
    - Medium Tier Worth 5 Scrap: Higher Tier Keycards (Not 05, Facility Manager, Chaos, or Captain),  SCP Items that spawn more than one (SCP-500, Vase). Guns (not FR-MGO, E11, Logicer).
    - High Tier Items Worth 10 Scrap: SCP items that only one spawn (Hat, Goggles, etc), Experimental Weapons (Micro, Jailbird, Disruptor), High Tier Guns (E11, Logicer, FRMGO). 
  - [x] Creating Item: Pressing LEFT ALT without an item in your hand creates the item using the scrap they have.
    - Have a dictionary of items and the associated number of scrap. This can be roughly up to you and what others suggest. Better items take more scrap. For now when trying to create an item it takes the highest level item that you can make with the scrap you have. You can have scrap left over. For instance if you have 12 scrap and the possible items are Medkit 5 scrap, Com15 10 scrap, and Captain Card 15 scrap. It will make the COM15 and use up 10 scrap and the player will have 2 scrap left over.

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discord.com/channels/956245649534378124/1308893828891148358/1308893828891148358
