### ISSUE TITLE
[API] Fix Map API To Work On 14.0 and Stabilize For Release

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#89]
**Task/Expectations:**
- [x] Fix errors so that maps load in 14.0.
- [x] Fix any known issues from the day of having it released on 13.5.
- Medbay:
  - [x] Fix door spawning in the void.
- Holding Cell:
  - [x] Fix SCP items spawning out of their pedastol.
- Entrance Armory:
  - [x] Fix door not spawning in proper place.
  - [x] Fix SRA being covered up by door wall.
- SCP-1499 Room:
  - [x] Move entrance door and make it work. 
  - [x] Move location of SCP-1499 room so it doesn't collide with 106 room.
- Wanders Library:
  - [x] Fix hazard so its not a collider occupying the whole room.
- [x]  Make a way to spawn guarenteed rooms just on map servers. (So theres guarenteed spawns for non map and map and ones for just map).
- [x] Fix custom loot not always spawning.
- [x] Add straight damage to room hazard.
- [x] Have QA Test all rooms and systems.
- [x] Live test.
