### ISSUE TITLE
[API] Stabalization

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#90]
**Description:**
Stabilizing plugins in a state where we were back to where we were on 13.5.

**Task Expectations/To Do:**
- [x] MER Integration for items/abilities.
- [x] Fix programs plugins so we can have all of his plugins on the server.
  - [x] Remote Keycard
  - [x] Modtools
  - [x] Funny Pills
  - [x] Afk Replacer
  - [x] Late Spawn
- [x] Make custom Firearms usable.
- [x] Add back items that use primatives.
- [x] Add back version of custom map that spawns important stuff (duel, shooting range, 1499).
- [x] Add custom maps back on server.

**Comment by jmoore34** [comment]
🦆

**Comment by TtroubleTT** [comment]
Fixed
