### ISSUE TITLE
[New Item] FSAS

### ISSUE THREAD

**Issue by TtroubleTT** [ChaosTheoryScp/IssueTracker#98]
**Description:**
An item when dropped spawns a device that when an enemy gets close they will be slowed and you will get a notification.

**Task Expectations/To Do:**
- [ ] Dropping will spawn a device that will alert you of nearby allies and slow them.
   - Spawns a custom model on activation. Model should be something not super noticeable. 
   - When an enemy gets close to the device (doesn't have to collide with it) they will be drastically slowed (some high slowness intensity) for 15 seconds. The placer who placed the device will also get a message about what enemy who triggered the device. The device will be destroyed upon activation. 
   - Multiple devices can be active at the same time and this should be accounted for. The message to the player who placed it should probably have the room in the message of the device so that they know which device activated.
   - Gives tracked effect for 20 seconds and the person who placed the FSAS can see the footsteps.
 - [ ] Spawn Rarity: Uncommon 
 - [ ] Item Category: Utility
 - [ ] Spawn on Hunter

[Note This To Reference The Idea The Task Above Itself Should Be Priority.  Ideas Change A Lot From The Initial Idea.]
**Discord Link:** https://discordapp.com/channels/956245649534378124/1249899838498406472/1249899838498406472
